name: Déploiement FTP automatique

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Déployer via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.0.0
        with:
          server: ftp.rca-emergency.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /htdocs/pharma.rca-emergency.com
/
